# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0002_auto_20170327_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='photographylistpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='photographypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='websitepage',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider1_title',
            field=models.CharField(default="We're a", help_text='maximum length 20 characters', max_length=20),
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
        migrations.DeleteModel(
            name='PhotographyListPage',
        ),
        migrations.DeleteModel(
            name='PhotographyPage',
        ),
        migrations.DeleteModel(
            name='ServicePage',
        ),
        migrations.DeleteModel(
            name='WebsitePage',
        ),
    ]
