# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170327_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='slider1_title_em',
            field=models.TextField(default='Digital Studio', help_text='maximum length 40 characters, emphasize character', max_length=40),
        ),
    ]
