# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_slider1_title_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='slider1_subtitle',
            field=models.TextField(default='Photography and Web Development at one Best Place', help_text='maximum legnth 100, subtitle in slider 1', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider2_title',
            field=models.TextField(default='is a worth a thousand words', help_text='maximum length is 70 characters', max_length=70),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider2_title_em',
            field=models.CharField(default='Picture', help_text='maximum length 20 characters and emphasize', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider3_title',
            field=models.CharField(default='based in', help_text='maximum length 20 characters', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider3_title_2',
            field=models.CharField(default='Downtown', help_text='maximum length 20 characters', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider3_title_em',
            field=models.CharField(default='Los Angeles', help_text='maximum length 20 characters emphasize', max_length=20),
        ),
    ]
