# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0005_auto_20170327_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='page_body_subtitle_1',
            field=models.CharField(default='We', help_text='maximum length 20 characters', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_body_subtitle_2',
            field=models.CharField(default='like minimal.', help_text='maximum length 20 characters', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_body_subtitle_em',
            field=models.CharField(default='really', help_text='maximum length 20 characters, emphasize', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_body_title_1',
            field=models.CharField(default="We're a", help_text='maximum length 20 characters', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_body_title_1_em',
            field=models.TextField(default='digital studio', help_text='maximum length 30 characters, emphasize', max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_body_title_2',
            field=models.TextField(default='that believe in the word of', help_text='maximum length 70 characters', max_length=70),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_body_title_2_em',
            field=models.TextField(default='less is more', help_text='maximum length 30 characters, emphasize', max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider1_image',
            field=models.ForeignKey(help_text='Image size must be 1680 x 1100', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider2_image',
            field=models.ForeignKey(help_text='Image size must be 1680 x 1100', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider3_image',
            field=models.ForeignKey(help_text='Image size must be 1680 x 1100', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider3_title',
            field=models.CharField(default='Based in', help_text='maximum length 20 characters', max_length=20),
        ),
    ]
