# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_photographypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographypage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(default='This is body of this page.'),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='main_title',
            field=models.TextField(default='Art of Still Image', help_text='Max Length is 40 characters', max_length=40),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='subtitle',
            field=models.TextField(default='WLM Studio', help_text='Subtitle, Max Length is 100 characters', max_length=100),
        ),
    ]
