# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0008_auto_20170328_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographypage',
            name='portfolio_image_1',
            field=models.ForeignKey(help_text='1100 x 650 px images.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='portfolio_image_2',
            field=models.ForeignKey(help_text='1100 x 650 px images.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='portfolio_image_3',
            field=models.ForeignKey(help_text='1100 x 650 px images.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='portfolio_image_4',
            field=models.ForeignKey(help_text='1100 x 650 px images.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='portfolio_image_5',
            field=models.ForeignKey(help_text='1100 x 650 px images.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
