# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_websitepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepage',
            name='title_1_end',
            field=models.TextField(default='that make', help_text='Max Length is 100 characters', max_length=100),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='title_1_front',
            field=models.CharField(default="We're a", help_text='Max Length is 20 characters', max_length=20),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='title_2_em_end',
            field=models.TextField(default='less code', help_text='Max Length is 40 characters', max_length=40),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='title_2_front',
            field=models.TextField(default='the most functional code out of', help_text='Max Length is 60 chracters', max_length=60),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='title_em_middle',
            field=models.TextField(default='Web Developer', help_text='Max Length is 40 characters', max_length=40),
        ),
    ]
