# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170328_0314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebsitePage',
            new_name='WebsitesPage',
        ),
    ]
