# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0013_websitepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitepage',
            name='category',
        ),
        migrations.AddField(
            model_name='websitepage',
            name='image_left_bottom',
            field=models.ForeignKey(help_text='Left Bottom image, 600 x 400 px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='image_left_top',
            field=models.ForeignKey(help_text='Left Top image, 600 x 400 px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='image_right',
            field=models.ForeignKey(help_text='Right side image, 1200 x 800 px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='main_hero_image',
            field=models.ForeignKey(help_text='Hero Image, 1680 x 1100 px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='project_category',
            field=models.CharField(default='E-Commerce', help_text='Project Category, 70 characters max', max_length=70),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='project_description',
            field=wagtail.wagtailcore.fields.RichTextField(default='Describe Proejct Detail'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='project_title',
            field=models.CharField(default='We like minimal', help_text='Project Name, 40 chracters max', max_length=40),
        ),
    ]
