# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20170329_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='E-Commerce', help_text='Name of Website category, max length is 25', max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='websitepage',
            name='website_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.WebsiteCategory'),
        ),
    ]
