# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0015_auto_20170329_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepage',
            name='thumbnail_image',
            field=models.ForeignKey(help_text='Thumbnail image for Website List Page. choose from 600 x 400, 600 x 600, 600 x 500', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
