# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_websitepage_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepage',
            name='brief_description_left_col',
            field=wagtail.wagtailcore.fields.RichTextField(default='Brief Description in Left Column'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='brief_description_right_col',
            field=wagtail.wagtailcore.fields.RichTextField(default='Brief Description in Right Column'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='brief_subtitle',
            field=wagtail.wagtailcore.fields.RichTextField(default='Brieft Subtitle'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='brief_title',
            field=models.CharField(default='New Design, New Photography', help_text='Brief title, 40 Max Length', max_length=40),
        ),
    ]
