# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 18:49
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20170405_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='main_subtitle',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='main_subtitle_first',
            field=wagtail.wagtailcore.fields.RichTextField(default='Main Subtitle First Line'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='main_subtitle_second',
            field=wagtail.wagtailcore.fields.RichTextField(default='Main Subtitle Second Line'),
        ),
    ]
