# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20170405_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='first_plan_description',
            field=wagtail.wagtailcore.fields.RichTextField(default='Description for first plan'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='first_plan_description_2',
            field=wagtail.wagtailcore.fields.RichTextField(default='Description for first plan in second price table'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='first_plan_description_3',
            field=wagtail.wagtailcore.fields.RichTextField(default='Description for first plan in third price table'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='first_plan_name',
            field=models.CharField(default='Basic', help_text='First plan name for first price table, 20 Max Characters', max_length=20),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='first_plan_name_2',
            field=models.CharField(default='Basic', help_text='First plan name for second price table, 20 Max Characters', max_length=20),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='first_plan_name_3',
            field=models.CharField(default='Event & On Location', help_text='First plan name for third price table, 40 Max Characters', max_length=40),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='first_plan_price',
            field=models.CharField(default='From $1495', help_text='40 Max Characters', max_length=40),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='first_plan_price_2',
            field=models.CharField(default='From $2495', help_text='40 Max Characters', max_length=40),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='first_plan_price_3',
            field=models.CharField(default='$250 per hour', help_text='40 Max Characters', max_length=40),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='first_subtitle',
            field=models.TextField(default='First Subtitle', help_text='100 Max Characters', max_length=100),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='first_title',
            field=models.CharField(default='Website', help_text='Price Table Title, 20 Max Characters', max_length=20),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='second_plan_description',
            field=wagtail.wagtailcore.fields.RichTextField(default='Description for second plan'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='second_plan_description_2',
            field=wagtail.wagtailcore.fields.RichTextField(default='Description for second plan in second price table'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='second_plan_description_3',
            field=wagtail.wagtailcore.fields.RichTextField(default='Description for second plan in third price table'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='second_plan_name',
            field=models.CharField(default='Premium', help_text='Second plan name for first price table, 20 Max Characters', max_length=20),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='second_plan_name_2',
            field=models.CharField(default='Premium', help_text='Second plan name for second price table, 20 Max Characters', max_length=20),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='second_plan_name_3',
            field=models.CharField(default='Apparel & Product', help_text='Second plan name for third price table, 40 Max Characters', max_length=40),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='second_plan_price',
            field=models.CharField(default='From $3495', help_text='40 Max Characters', max_length=40),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='second_plan_price_2',
            field=models.CharField(default='From 3495', help_text='40 Max Characters', max_length=40),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='second_plan_price_3',
            field=models.CharField(default='Charged by piece', help_text='40 Max Characters', max_length=40),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='second_subtitle',
            field=models.TextField(default='Second Subtitle', help_text='100 Max Characters', max_length=100),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='second_title',
            field=models.CharField(default='E-Commerce', help_text='Price Table Title, 20 Max Characters', max_length=20),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='third_plan_description',
            field=wagtail.wagtailcore.fields.RichTextField(default='Description for third plan'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='third_plan_description_2',
            field=wagtail.wagtailcore.fields.RichTextField(default='Description for third plan in second price table'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='third_plan_name',
            field=models.CharField(default='Ultimate', help_text='Third plan name ofr first price table, 20 Max Characters', max_length=20),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='third_plan_name_2',
            field=models.CharField(default='Ultimate', help_text='Third plan name for second price table, 20 Max Characters', max_length=20),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='third_plan_price',
            field=models.CharField(default='From $7495', help_text='40 Max Characters', max_length=40),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='third_plan_price_2',
            field=models.CharField(default='From $6495', help_text='40 Max Characters', max_length=40),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='third_subtitle',
            field=models.TextField(default='Third Subtitle', help_text='100 Max Characters', max_length=100),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='third_title',
            field=models.CharField(default='Photography', help_text='Price Table Title, 20 Max Characters', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='first_quote',
            field=wagtail.wagtailcore.fields.RichTextField(default="When you don't create things, you become defined by your tastes rather than ability. your tastes only narrow & exclude people. so create."),
        ),
    ]
