# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0022_auto_20170406_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='description_left_col',
            field=wagtail.wagtailcore.fields.RichTextField(default='Company Description in Left Column'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='description_right_col',
            field=wagtail.wagtailcore.fields.RichTextField(default='Company Description in Right Column'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='est_image',
            field=models.ForeignKey(help_text='Established Logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_image',
            field=models.ForeignKey(help_text='Hero Parallax image, 1680 x 1100', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='main_title',
            field=models.TextField(default='Distinctive and striking digital products', help_text='Main title in the page, 200 Max Characters', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='title_back',
            field=models.TextField(default='based in Los Angeles, crafting digital experiences.', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='title_em',
            field=models.CharField(default='Web Agency + Photo Studio', help_text='Emphasize letter, 40 Max Characters', max_length=40),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='title_front',
            field=models.CharField(default='We are the', help_text='First few letters before emphasize letter', max_length=20),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='title_small',
            field=models.CharField(default='Where the Arts and Technology converge', help_text='First line in the page, 70 Max Characters', max_length=70),
        ),
    ]
