# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20170406_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='contact_title',
            field=models.TextField(default='Interested in working with us?', help_text='100 Max Characters', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_title_alt',
            field=models.TextField(default='We enjoy meeting new people', help_text='100 Max Characters', max_length=100),
        ),
    ]
