# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 21:20
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20170407_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactpage',
            old_name='intro',
            new_name='intro_2',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='intro_1',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default='Start a new project?'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='intro_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default='For quotes on new projects, please fill out our inquiry form and we can direct you to the right team.'),
        ),
    ]
