# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_inquirepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryFormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.CharField(blank=True, help_text='Default value. Comma separated values supported for checkboxes.', max_length=255, verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='inquirepage',
            name='from_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='from address'),
        ),
        migrations.AddField(
            model_name='inquirepage',
            name='main_subtitle',
            field=models.TextField(default='We will get back to you within 48 hours.', help_text='Main subtitle, 200 max characters', max_length=200),
        ),
        migrations.AddField(
            model_name='inquirepage',
            name='main_title_1',
            field=models.CharField(default='Make an inquiry', help_text='first few letters in main title, 40 Max Characters', max_length=40),
        ),
        migrations.AddField(
            model_name='inquirepage',
            name='main_title_2',
            field=models.CharField(default='for', help_text='second line in main title, 40 max characters', max_length=40),
        ),
        migrations.AddField(
            model_name='inquirepage',
            name='main_title_em',
            field=models.CharField(default='New Project', help_text='Emphasize letter in main title, 40 max characters', max_length=40),
        ),
        migrations.AddField(
            model_name='inquirepage',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='inquirepage',
            name='thank_you_text',
            field=wagtail.wagtailcore.fields.RichTextField(default='Thank you'),
        ),
        migrations.AddField(
            model_name='inquirepage',
            name='to_address',
            field=models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, verbose_name='to address'),
        ),
        migrations.AddField(
            model_name='inquiryformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_fields', to='home.InquirePage'),
        ),
    ]
