# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 00:22
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20170407_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirepage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(default='Please tell us more about your company'),
        ),
    ]
