# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0031_photoinquirepage_photoinquiryformfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographypage',
            name='portfolio_image_6',
            field=models.ForeignKey(help_text='1100 x 650 px images.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='portfolio_image_7',
            field=models.ForeignKey(help_text='1100 x 650 px images.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='portfolio_image_8',
            field=models.ForeignKey(help_text='1100 x 650 px images.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
