# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20170409_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='first_subtitle',
            field=models.TextField(default='First Subtitle', help_text='100 Max Characters', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='second_subtitle',
            field=models.TextField(default='Second Subtitle', help_text='100 Max Characters', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='third_subtitle',
            field=models.TextField(default='Third Subtitle', help_text='100 Max Characters', max_length=200),
        ),
    ]
