# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0033_auto_20170410_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='fifth_image',
            field=models.ForeignKey(help_text='300 x 300 px image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='first_image',
            field=models.ForeignKey(help_text='300 x 300 px image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='fourth_image',
            field=models.ForeignKey(help_text='300 x 300 px image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='second_image',
            field=models.ForeignKey(help_text='300 x 300 px image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='sixth_image',
            field=models.ForeignKey(help_text='300 x 300 px image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='third_image',
            field=models.ForeignKey(help_text='300 x 300 px image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='what_we_do_first',
            field=models.CharField(default='Websites', help_text='20 Max Characters', max_length=20),
        ),
    ]
