# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0035_auto_20170410_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitepage',
            name='brief_description_left_col',
        ),
        migrations.RemoveField(
            model_name='websitepage',
            name='brief_description_right_col',
        ),
        migrations.RemoveField(
            model_name='websitepage',
            name='brief_subtitle',
        ),
        migrations.RemoveField(
            model_name='websitepage',
            name='brief_title',
        ),
        migrations.RemoveField(
            model_name='websitepage',
            name='image_left_bottom',
        ),
        migrations.RemoveField(
            model_name='websitepage',
            name='image_left_top',
        ),
        migrations.RemoveField(
            model_name='websitepage',
            name='image_right',
        ),
        migrations.RemoveField(
            model_name='websitepage',
            name='main_hero_image',
        ),
        migrations.RemoveField(
            model_name='websitepage',
            name='thumbnail_image',
        ),
        migrations.AddField(
            model_name='websitepage',
            name='website_image_1',
            field=models.ForeignKey(help_text='1100 x 650 px images.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='website_image_2',
            field=models.ForeignKey(help_text='1100 x 650 px images.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='website_image_3',
            field=models.ForeignKey(help_text='1100 x 650 px images.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='website_image_4',
            field=models.ForeignKey(help_text='1100 x 650 px images.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='website_url',
            field=models.URLField(default='www.welikeminimal.com'),
        ),
    ]
