# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0036_auto_20170413_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepage',
            name='thumbnail_image',
            field=models.ForeignKey(help_text='600 x anysize(400, 600, 800) px image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
