# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_websitepage_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='slider1_subtitle',
            field=models.TextField(default='Photography and Web Development at one Best Place', help_text='maximum legnth 200, subtitle in slider 1', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider1_title',
            field=models.TextField(default="We're a", help_text='maximum length 100 characters', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider1_title_em',
            field=models.TextField(default='Digital Studio', help_text='maximum length 100 characters, emphasize character', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider2_title',
            field=models.TextField(default='is a worth a thousand words', help_text='maximum length is 200 characters', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider2_title_em',
            field=models.TextField(default='Picture', help_text='maximum length 100 characters and emphasize', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider3_title',
            field=models.TextField(default='Based in', help_text='maximum length 100 characters', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider3_title_2',
            field=models.TextField(default='Downtown', help_text='maximum length 20 characters', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider3_title_em',
            field=models.TextField(default='Los Angeles', help_text='maximum length 20 characters emphasize', max_length=100),
        ),
    ]
