# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_basicpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='service_col_1_description',
            field=wagtail.wagtailcore.fields.RichTextField(default='Description for service'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_col_1_header',
            field=models.CharField(default='Website Design & Development', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_col_2_description',
            field=wagtail.wagtailcore.fields.RichTextField(default='Description for service'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_col_2_header',
            field=models.CharField(default='E-Commerce Web Development', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_col_3_description',
            field=wagtail.wagtailcore.fields.RichTextField(default='Description for service'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_col_3_header',
            field=models.CharField(default='Digital Marketing Strategy', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_col_4_description',
            field=wagtail.wagtailcore.fields.RichTextField(default='Description for service'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_col_4_header',
            field=models.CharField(default='Creative Photographer', max_length=100),
        ),
    ]
