# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20170513_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepage',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
